name: Build and test

on: [push, pull_request]

jobs:
  build:
    runs-on: windows-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: Install Windows dependencies
      shell: pwsh
      run: |
        choco install llvm --yes --no-progress
    - name: Checkout submodules
      run: git submodule update --init
    - name: Create build directory
      run: mkdir build
    - name: CMake
      run: cd build && cmake ..
    - name: Build (Windows)
      shell: pwsh
      run: cmake --build build --config Release
    - name: Run tests (Windows)
      shell: pwsh
      run: ./build/tests/Release/tests.exe
    - name: Upload build artifacts (Windows)
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: windows-build-${{ github.sha }}
        if-no-files-found: warn
        path: |
          build/tests/Release/tests.exe
          build/src/Release/*.lib
          build/src/Release/*.dll
